theme: jekyll-theme-minimal
title: Found these AirPods?
description: <br>Were they laying around somewhere? Classic me to forget something of such importance. But you, you are an outstanding citizen for finding these and bringing them back to me
logo: https://media.giphy.com/media/DhstvI3zZ598Nb1rFf/giphy-downsized-large.gif
show_downloads: "false"
